  version: 2.2
  hooks:
    - type: pre-commit
      actions:
        - name: "Hinge"
          url: https://github.com/devops-kung-fu/hinge/releases/download/v0.1.0/hinge-0.1.0-linux-amd64
          args: ["."]
        - name: "Add all changed files during the pre-commit stage"
          exec: git
          args: ["add", "."]
